services:
  # Backend API Service
  - type: web
    name: library-backend
    runtime: node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    buildpacks:
      - heroku/nodejs 